// generated by Fast Light User Interface Designer (fluid) version 1.0109

#ifndef window_h
#define window_h
#include <FL/Fl.H>
void bt_callback(Fl_Widget*, void* userdata);
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *window_main;
#include <FL/Fl_Input.H>
extern Fl_Input *input;
#include <FL/Fl_Button.H>
extern Fl_Button *btnTest;
#include <FL/Fl_Return_Button.H>
extern Fl_Return_Button *btnClose;
#include <FL/Fl_Slider.H>
extern void sldr_callback(Fl_Slider*, void*);
extern Fl_Slider *slider1;
#include <FL/Fl_Dial.H>
extern void dial1_callback(Fl_Dial*, void*);
extern Fl_Dial *dial1;
extern void dial2_callback(Fl_Dial*, void*);
extern Fl_Dial *dial2;
#include <FL/Fl_Text_Display.H>
extern Fl_Text_Display *tdisp;
Fl_Double_Window* createWindow();
#endif
