// generated by Fast Light User Interface Designer (fluid) version 1.0109

#include "window.h"
#include <iostream>
#include <cstdlib>
#include <cstdio>

using namespace std;

void bt_callback(Fl_Widget*, void* userdata) {
  if(userdata == "test")
	std::cout << "Testing" << std::endl;
else if (userdata == "close")
	exit(0);
}

Fl_Double_Window *window_main=(Fl_Double_Window *)0;

Fl_Input *input=(Fl_Input *)0;

Fl_Button *btnTest=(Fl_Button *)0;

Fl_Return_Button *btnClose=(Fl_Return_Button *)0;

Fl_Slider *slider1=(Fl_Slider *)0;

Fl_Dial *dial1=(Fl_Dial *)0;

Fl_Dial *dial2=(Fl_Dial *)0;

Fl_Text_Display *tdisp=(Fl_Text_Display *)0;

Fl_Double_Window* createWindow() {
  { window_main = new Fl_Double_Window(755, 415, "FLTK window 1");
    window_main->tooltip("main window");
    window_main->box(FL_GTK_THIN_DOWN_BOX);
    window_main->align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE);
    { input = new Fl_Input(145, 10, 150, 25, "Please enter value:");
    } // Fl_Input* input
    { btnTest = new Fl_Button(10, 100, 100, 25, "Test");
      btnTest->callback((Fl_Callback*)bt_callback, (void*)("test"));
    } // Fl_Button* btnTest
    { btnClose = new Fl_Return_Button(195, 100, 100, 25, "Close");
      btnClose->callback((Fl_Callback*)bt_callback, (void*)("close"));
    } // Fl_Return_Button* btnClose
    { slider1 = new Fl_Slider(303, 11, 25, 117);
      slider1->maximum(255);
      slider1->step(1);
      slider1->callback((Fl_Callback*)sldr_callback);
    } // Fl_Slider* slider1
    { dial1 = new Fl_Dial(333, 10, 25, 25);
      dial1->maximum(255);
      dial1->step(1);
      dial1->callback((Fl_Callback*)dial1_callback);
    } // Fl_Dial* dial1
    { dial2 = new Fl_Dial(334, 38, 25, 25);
      dial2->maximum(255);
      dial2->step(1);
      dial2->callback((Fl_Callback*)dial2_callback);
    } // Fl_Dial* dial2
    { tdisp = new Fl_Text_Display(374, 25, 91, 25);
    } // Fl_Text_Display* tdisp
    window_main->end();
  } // Fl_Double_Window* window_main
  return window_main;
}
